version: '2'
services:
  reactjhipster-app:
    image: reactjhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://reactjhipster-mariadb:3306/reactjhipster?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_CACHE_REDIS_SERVER=redis://reactjhipster-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://reactjhipster-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  reactjhipster-mariadb:
    extends:
      file: mariadb.yml
      service: reactjhipster-mariadb
  reactjhipster-redis:
    extends:
      file: redis.yml
      service: reactjhipster-redis
